@host = ws://localhost:8090

# ======================================================================================================================
# Get unoccupied spots

###
GET {{host}}/api/v1/spot/unoccupied